### PR TITLE
ux: Make nested and/or triggers a bit easier to read

### LINKED ISSUE #125: And / Or functionality
### Category

Question about a Trigger

### Question

I'm not sure what's going on, but the following didn't work:

cooking-and-or

but this one did:

cooking-or-and

Posting this as a question since I'm not sure if I'm doing something wrong or it's a bug since they should be functionally equivalent as:

`(Item Quantity Magma Fish >= 10000 && Mastery Level Cooking: Magma Fish == 99) || (Item Quantity Raw Magma Fish <= 0)`

It wouldn't matter if the first way was interpreted as:

`(Item Quantity Magma Fish >= 10000) && (Mastery Level Cooking: Magma Fish == 99 || Item Quantity Raw Magma Fish <= 0)`

since it should have still changed to the next task as I had more than 10k Magma Fish and hit 99 mastery level in it as well.

### Code of Conduct

- [X] I agree to follow the code of conduct
- [X] I have searched for similar issues and nothing similar exists

### PR DESCRIPTION
**Pull request by Alorel**
Closes #125

@kellewic have a look - do the extra borders make it a bit clearer on how conditions get nested?

<details>
<summary>Screenshot</summary>

image

</details>

### CODE REVIEW

**Comment by kellewic** [comment]
The borders do. From how I read it, it would be `OR(C1, AND(C2, C3))` if I were to express this as embedded function calls with the AND() really being a condition of the OR.

I'm wondering what all the Trash/Plus icon combos are for.

The first one to add another OR condition? If so, what's the last one for at the bottom?
I assume the icons inside the AND triggers will both add another AND condition.

**Comment by Alorel** [comment]
> I'm wondering what all the Trash/Plus icon combos are for.

They're for removing conditions and adding more of them - the mod used to only let you add workflow steps at the end of the array, but folk wanted to be able to insert stuff in the middle so I just extended the same logic to and/or triggers. The trash icons should then be self-explanatory, as for the `+`s, going top to bottom:

1. Adds an extra OR condition in between raw magma fish & the `AND`
2. Adds an extra AND condition in between magma fish quantity & mastery level
3. Adds an extra AND condition after mastery level
4. Adds an extra OR condition after the AND trigger

Ehh it's not like we're short on screen space here, might as well just refactor the buttons to use text instead of icons - if you got confused by them then more people definitely have as well. Thanks a ton for feedback like this btw - I wrote this stuff so I'm **very** biased re: what seems clear in the UI and what doesn't :slightly_smiling_face:

**Comment by Alorel** [comment]
Got another attempt ready - I reckon it's readable _enough_?

<details>
<summary>Desktop sceenshot</summary>

melvoridle com_index_game php

</details>

<details>
<summary>Mobile screenshot</summary>

melvoridle com_index_game php (1)

</details>

**Comment by kellewic** [comment]
> Got another attempt ready - I reckon it's readable _enough_?
> 
Looks really nice and makes it more understandable with the very specific borders. The icons were ok, but I like the words better.

**Comment by Alorel** [comment]
Good stuff, glad we found a way to improve it :)

**Pull request merged**
